### ISSUE TITLE
Something is breaking site menu

### ISSUE THREAD

**Issue by juho-jaakkola** [sbwtech/sbw#43]
The site menu does not get opened on front page. This is most likely a bug in Landr plugin.

**Comment by michelesbw** [comment]
I am seeing this after changes made to add square logo for mobile version...just a coincidence?

**Comment by juho-jaakkola** [comment]
Landr is causing it:
```css
#login-dropdown, .elgg-menu-site {
    display: none;
}
```
